### ISSUE TITLE
Is juj's pthreads still alive and kicking?

### ISSUE THREAD

**Issue by httpdigest** [kripken/emscripten-fastcomp#113]
After some time of inactivity I am trying to revive my attempt on porting JamVM to Emscripten.
I just want to know whether the development of pthreads support in Emscripten is still continued or whether focus/effor will be shifting towards WebAssembly now.

I know this question should rather be posted on juj's repository, but there is no Issue tracker there.
Thanks!

**Comment by juj** [comment]
The pthread support is well alive and going on. The intention is that the WebAssembly pthreads support builds directly on the current Emscripten support and the SharedArrayBuffer specification, so there is no shift of focus happening. It is possible that some things will change (even drastically!) if we learn that the SAB spec should be done somehow different in places, since after all it is still researchy.

**Comment by httpdigest** [comment]
Cool, thanks for the heads-up! It's good to hear that it is actively maintained/developed.
