### ISSUE TITLE
Attempt to merge LLVM git master

### ISSUE THREAD

**Issue by ricejasonf** [kripken/emscripten-fastcomp#144]
I took a stab at merging llvm and clang from the git mirror master branches into the emscripten-fastcomp/clang repos. I resolved the conflicts and made a few changes which can be viewed here: https://github.com/ricejasonf/emscripten-fastcomp/commit/c24408dd6635bb5d3cbf8b913e0e778bb3ea10a5

It's mostly just name changes and whitespace stuff plus a minor change to the use of a `StringRef` in a warning and the elimination of `CodeGenInfo` which is apparently not used anymore in `TargetMachine` (I could be very wrong).

The fastcomp stuff with the changes compiles and emscripten's `test_hello_world` passes, but some tests do not pass for example `test_dynamic_cast`:

```
test_dynamic_cast (test_core.default) ... (checking sanity from test runner)
INFO:root:(Emscripten: Running sanity checks)
(test did not pass in JS engine: ['/usr/bin/nodejs'])
ERROR

======================================================================
ERROR: test_dynamic_cast (test_core.default)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/src/emscripten/tests/test_core.py", line 1730, in test_dynamic_cast
    self.do_run_from_file(src, output)
  File "/usr/local/src/emscripten/tests/runner.py", line 601, in do_run_from_file
    includes, force_c, build_ll_hook, extra_emscripten_args)
  File "/usr/local/src/emscripten/tests/runner.py", line 635, in do_run
    raise e
Exception: Expected to find 'f()
' in '5
Invalid function pointer called with signature 'viiiiii'. Perhaps this is an invalid value (e.g. caused by calling a virtual method on a NULL pointer)? Or calling a function with an incorrect type, which will fail? (it is worth building your source files with -Werror (warnings are errors), as warnings can indicate undefined behavior which can cause this)
Build with ASSERTIONS=2 for more info.
5
```

It is also worth mentioning that when emscripten was generating system libraries I got several warnings like the following:
```
WARNING:root:generating system library: dlmalloc.bc...
/usr/local/src/emscripten/system/lib/dlmalloc.c:617:5: warning: macro expansion producing 'defined' has
      undefined behavior [-Wexpansion-to-defined]
#if USE_LOCKS /* Spin locks for gcc >= 4.1, older gcc on x86, MSC >= 1310 */
    ^
/usr/local/src/emscripten/system/lib/dlmalloc.c:613:22: note: expanded from macro 'USE_LOCKS'
#define USE_LOCKS  ((defined(USE_SPIN_LOCKS) && USE_SPIN_LOCKS != 0) || \
```

I'd like to figure out if any of the changes that I made are causing this, (The `CodeGenInfo` thing is suspicious) or if perhaps there are necessary changes I need to make in the `emscripten` repo.

Any help is greatly appreciated. Thank you.

**Comment by kripken** [comment]
Thanks for looking into this!

I've actually been doing the same recently, and looking at your changes they are almost identical to mine, see the `next-merge` branches in the `fastcomp` and `fastcomp-clang` repos. (Maybe in the future I should open an issue before doing this work, to avoid duplication.)

The issues you ran into look like ones I saw, too. Those warnings appear to be just that clang warns about more things now. If it's feasible we should get rid of those warnings by modifying those system files, however, we also prefer to not modify musl and dlmalloc files as they are from other projects, and it's simpler if we have no changes. But if the changes are simple, might be worth it. I didn't look into that.

I also hit a problem with dynamic cast, like you. I believe the issue was a change in how LLVM does data layout offset calculations, they replaced `getIndexedOffset` with `getIndexedOffsetInType`, and it expects a different type than before (the element type instead of the pointer type, or vice versa, it's all very confusing...). This was an issue in `FlattenLocals's `ExpandConstant`, when I had it wrong it broke dynamic cast.

At this stage, the `next-merge` branches seem to be ready to be merged into incoming, tests passed on my machine locally. Maybe you can take a look and test it?

**Comment by ricejasonf** [comment]
Ah, sweet! I will definitely check it out.

**Comment by ricejasonf** [comment]
Using next-merge branch, I ran "random100" and both `test_sse1_full` and `test_sse2_full` *failed*. Let me know if you want to post output. It is verbose.

**Comment by kripken** [comment]
Sounds like https://github.com/kripken/emscripten/issues/4435, are you using the `next-merge` branch in emscripten? It has a workaround commit for that.

**Comment by ricejasonf** [comment]
Yeah, sorry, my emscripten repo was not on the right branch. Those two work now.

**Comment by kripken** [comment]
Good, thanks for verifying. Everything looks ok then?

**Comment by ricejasonf** [comment]
Yes. I ran random100 and they passed.

**Comment by ricejasonf** [comment]
:+1:
